services:
  testbed-api:
    platform: linux/amd64
    env_file: .env
    environment:
      SPRING_APPLICATION_JSON: '{"server":{"address":"0.0.0.0","port":4500}}'
    build: 
      context: .
      args:
        VERSION: "${VERSION}"
    ports:
      - "4500:4500"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    platform: linux/amd64
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres-data: