/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.testbed.api;

public class AppTest {
    /*
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    */
}
