/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.testbed.api.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(basePackages = "org.ga4gh.testbed.api")
public class TestbedApi {
    public static void main(String[] args) {
        SpringApplication.run(TestbedApi.class, args);
    }
}
